version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3006:3000"
      - "5561:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5441/orderflow
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5441:5432"
volumes:
  pgdata: